
lang: ru


clan-create:

  min-clan-tag-length: 3
  max-clan-tag-length: 6
  blocked-tags:
    - "admin"
    - "owner"
    - "op"
  member-rank: MEMBER # ВАЖНО: Укажите здесь ранг, который будет присвоен новому участнику клана при вступлении в клан
  leader-rank: LEADER # ВАЖНО: Укажите здесь ранг, который будет присвоен создателю клана при создании клана


chat-format: "<#FFE259>&l[TreexClans]</#FFA751> &e&l{player} &7▶ &f{message}"

# Если true то квесты будут выполнятся постепенно, то есть нельзя перейти на другой квесты пока не выполнишь предыдущий
# Если false то можно выполнить любой квест не смотря на очерёдность
gradual-quest: true

ranks:
  # можно создавать неограниченное количество рангов
  MEMBER:
    display-name: "&7Участник"
    permissions:
      invite: true
      kick: false
      base: true
      setbase: false
      setrank: false
      deposit: true
      withdraw: false
      pvp: false
  CONTROL:
    display-name: "&3Управляющий"
    permissions:
      invite: true
      kick: true
      base: true
      setbase: true
      setrank: false
      deposit: true
      withdraw: true
      pvp: true
  LEADER:
    display-name: "&4&lЛидер"
    permissions:
      invite: true
      kick: true
      base: true
      setbase: true
      setrank: true
      deposit: true
      withdraw: true
      pvp: true


placeholder-show-format: "%weeks% %days% %hours% %minutes%"