
clan-create:
  requirements:
    example:
      type: math
      express: "%vault_eco_balance_fixed% >= 5000"
      actions:
        - "[message] &aВы успешно создали клан &e{clan_tag}"
      deny_actions:
        - "[message] &cНедостаточно денег на создание клана! Минимум 5000 монет"
    "example2": {}

  min-clan-tag-length: 3
  max-clan-tag-length: 6
  blocked-tags:
    - "admin"
    - "owner"
    - "op"
  member-rank: MEMBER # ВАЖНО: Укажите здесь ранг, который будет присвоен новому участнику клана при вступлении в клан
  leader-rank: LEADER # ВАЖНО: Укажите здесь ранг, который будет присвоен создателю клана при создании клана


ranks:
  # можно создавать неограниченное количество рангов
  MEMBER:
    display-name: Участник
    permissions:
      invite: false
      kick: false
      base: false
      setbase: false
      setrank: false
      deposit: true
      withdraw: false
      pvp: false
  LEADER:
    display-name: Лидер
    permissions:
      invite: true
      kick: true
      base: true
      setbase: true
      setrank: true
      deposit: true
      withdraw: true
      pvp: true