
lang: ru

clan-create:
  requirements:
    example:
      type: math
      input: "%vault_eco_balance_fixed% >= 5000"
      actions:
        - "[money_take] 5000"
      deny_actions:
        - "[message] &cНедостаточно денег на создание клана! Минимум 5000 монет"
    "example2": {}

  min-clan-tag-length: 3
  max-clan-tag-length: 6
  blocked-tags:
    - "admin"
    - "owner"
    - "op"
  member-rank: MEMBER # ВАЖНО: Укажите здесь ранг, который будет присвоен новому участнику клана при вступлении в клан
  leader-rank: LEADER # ВАЖНО: Укажите здесь ранг, который будет присвоен создателю клана при создании клана


chat-format: "<#FFE259>&l[TreexClans]</#FFA751> &e&l{player} &7▶ &f{message}"

# Если true то квесты будут выполнятся постепенно, то есть нельзя перейти на другой квесты пока не выполнишь предыдущий
# Если false то можно выполнить любой квест не смотря на очерёдность
gradual-quest: false

ranks:
  # можно создавать неограниченное количество рангов
  MEMBER:
    display-name: Участник
    permissions:
      invite: false
      kick: false
      base: false
      setbase: false
      setrank: false
      deposit: true
      withdraw: false
      pvp: false
  LEADER:
    display-name: Лидер
    permissions:
      invite: true
      kick: true
      base: true
      setbase: true
      setrank: true
      deposit: true
      withdraw: true
      pvp: true