name: TreexClans
version: '1.0'
main: me.jetby.treexclans.TreexClans
api-version: '1.16'
load: POSTWORLD
authors: [ MrJetby ]
website: https://dsc.gg/treexstudio
softdepend:
  - Vault
  - packetevents
  - Treex
  - PlaceholderAPI
commands:
  xclan: {}
  clan: {}