name: TreexClans
version: '1.0'
main: me.jetby.xClans.TreexClans
api-version: '1.16'
load: STARTUP
authors: [ MrJetby ]
website: https://dsc.gg/treexstudio
depend:
  - packetevents
commands:
  xclan: {}
  clan: {}